### ISSUE TITLE
Script fails after converting a few posts

### ISSUE THREAD

**Issue by swishkin** [guywhataguy/Blogger-To-Markdown#1]
Here's the traceback:

`Traceback (most recent call last):
  File "C:\Users\noah\Downloads\CSAM Conversion\convert_blogger_xml_to_md.py", line 502, in <module>
    main()
  File "C:\Users\noah\Downloads\CSAM Conversion\convert_blogger_xml_to_md.py", line 492, in main
    convert_posts_to_md(sys.argv[1])
  File "C:\Users\noah\Downloads\CSAM Conversion\convert_blogger_xml_to_md.py", line 475, in convert_posts_to_md
    convert_post_to_md(entry, output_md_formatter)
  File "C:\Users\noah\Downloads\CSAM Conversion\convert_blogger_xml_to_md.py", line 432, in convert_post_to_md
    post_data["md"] = convert_html_to_md(post_xml.find("{http://www.w3.org/2005/Atom}content").text)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noah\Downloads\CSAM Conversion\convert_blogger_xml_to_md.py", line 412, in convert_html_to_md
    parser.feed(html)
  File "C:\Users\noah\AppData\Local\Programs\Python\Python311\Lib\html\parser.py", line 109, in feed
    self.rawdata = self.rawdata + data
                   ~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "NoneType") to str`

It looks like py is calling 3.11, but I've also got 3.7 installed. Is any specific version needed to run the script?

**Comment by mavlevin** [comment]
Hey Swishkin, could you provide the xml you are trying to covert, or an excerpt from the xml that can reproduce the bug?

**Comment by swishkin** [comment]
I've found a different solution to this need and couldn't replicate the issue I encountered over two years ago...

Sorry for my late response!
